apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-h8wn
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lttm-tenant/rhtap-demo-app/hacbs-test-project-h8wn@sha256:43c23c5a60289c124cc790967dd9af955522a565907c1a14420c6fa74d9e91f8
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
